set-window-option -g mode-keys vi
set -g history-limit 50000

set -g mouse on
set -g default-terminal "tmux-256color"

# Start windows and panes at 1, not 0
set -g base-index 1
setw -g pane-base-index 1

bind r source-file ~/.tmux.conf ; display-message "Config reloaded!"

# don't rename windows automatically
set -g allow-rename off

# switch panes using Alt-arrow without prefix
bind -n M-Left select-pane -L
bind -n M-Right select-pane -R
bind -n M-Up select-pane -U
bind -n M-Down select-pane -D

bind e send-keys 'source ~/.zshrc' C-m

#bind-key e run-shell "bash -c '                                           
#file=\"$HOME/.tmux.env\"                                                  
#export_line=\"\"                                                          
#if [[ -f \$file ]]; then                                                  
#    while IFS=\"=\" read -r key value; do                                 
        # Skip empty lines or comments                                    
        #if [[ -n \$key && \$key != \#* ]]; then                          
            # Set tmux global environment variable                        
#            tmux set-environment \$key \$value                            
            # Safely escape key=value for shell export                    
#            export_line+=$(printf \"%q=%q \" \"\$key\" \"\$value\")       
   #     fi                                                               
#    done < \$file                                                         
    # Export all variables in the current pane                            
#    tmux send-keys \"export \$export_line\" C-m                           
#    tmux display-message \"Loaded env\"                                   
#else                                                                      
#    tmux display-message \"No file found\"                                
#fi'"                                                                      

set -g @logging-path "~/.tmux/logs"                                          
#run-shell ~/.tmux/plugins/tmux-logging/logging.tmux                          
#run-shell ~/.tmux/plugins/tmux-yank/yank.tmux                                
set -g @yank_selection 'clipboard'
set -g @custom_copy_command 'xclip -i -selection clipboard && xclip -i -selection primary'

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-logging'
set -g @plugin 'tmux-plugins/tmux-yank'

setenv -g TMUX_PLUGIN_MANAGER_PATH "$HOME/.tmux/plugins/"

if "test ! -d ~/.tmux/plugins/tpm" \
       "run 'git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm && ~/.tmux/plugins/tpm/bin/install_plugins'"

run '~/.tmux/plugins/tpm/tpm'
